steps:
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy","--verbosity","debug"]
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: 'bash'
  args: 
   - '-c'
   - |
      sed -i "s|##_PRIVATEKEY##|${_PRIVATEKEY}|g" app.yaml
      gcloud config set app/cloud_build_timeout 1600
      gcloud app deploy
timeout: "4800s"
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _PRIVATEKEY: ${_PRIVATEKEY}