steps:
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy","--verbosity","debug"]
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set project neon-metric-318616 && gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --verbosity debug']
  env:
    - 'MY_NAME=$_MYNAME'
timeout: "4800s"
options:
  logging: CLOUD_LOGGING_ONLY